version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./secrets/env/.env:/app/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/measuresdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
