version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

services:
  app:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      - MONGO_URI=mongodb://user:test@mongo:27017/measuresdb?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Interface que administra o MongoDB no servidor Web
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://user:test@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - app-network
